using System;
using System.Linq;
using System.Text;
using MedReminder.Models;

namespace MedReminder.Services
{
    public static class ResidentReportBuilder
    {
        // Option 1: HTML report that can be shared and printed
        public static string BuildHtml(ResidentReport report)
        {
            var resident = report.ResidentSnapshot;
            var meds = report.Medications ?? new();
            var observations = report.Observations ?? new();

            var sb = new StringBuilder();

            sb.AppendLine("<!doctype html>");
            sb.AppendLine("<html><head><meta charset='utf-8'>");
            sb.AppendLine("<meta name='viewport' content='width=device-width, initial-scale=1'>");
            sb.AppendLine("<title>Resident Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Arial, sans-serif; margin:24px; color:#111;}");
            sb.AppendLine("h1{margin:0 0 8px 0;} h2{margin-top:20px;}");
            sb.AppendLine(".muted{color:#666; font-size:12px;}");
            sb.AppendLine("table{border-collapse:collapse; width:100%; margin-top:8px;}");
            sb.AppendLine("th,td{border:1px solid #ddd; padding:8px; vertical-align:top;}");
            sb.AppendLine("th{background:#f5f5f5; text-align:left;}");
            sb.AppendLine(".chip{display:inline-block; padding:2px 8px; border-radius:999px; background:#eee; font-size:12px;}");
            sb.AppendLine("</style></head><body>");

            // Header
            sb.AppendLine("<h1>Resident Report</h1>");
            sb.AppendLine($"<div class='muted'>ReportId: {report.ReportId}</div>");
            sb.AppendLine($"<div class='muted'>Generated: {report.GeneratedAt:yyyy-MM-dd HH:mm}</div>");
            sb.AppendLine($"<div class='muted'>Generated by: {Html(report.GeneratedByStaff)}</div>");

            // Resident info (match your Resident.cs)
            sb.AppendLine("<h2>Resident Profile</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tr><th>ResidentId</th><td>" + report.ResidentId + "</td></tr>");
            sb.AppendLine("<tr><th>Name</th><td>" + Html(resident.FullName) + "</td></tr>");
            sb.AppendLine("<tr><th>DOB</th><td>" + Html(resident.DOB) + "</td></tr>");
            sb.AppendLine("<tr><th>SIN</th><td>" + Html(resident.SIN) + "</td></tr>");
            sb.AppendLine("<tr><th>Doctor</th><td>" + Html(resident.DoctorName) + "</td></tr>");
            sb.AppendLine("<tr><th>Doctor Contact</th><td>" + Html(resident.DoctorContact) + "</td></tr>");
            sb.AppendLine("<tr><th>Allergies</th><td>" + Html(resident.AllergyOtherItems) + "</td></tr>");
            sb.AppendLine("<tr><th>Remarks</th><td>" + Html(resident.Remarks) + "</td></tr>");
            sb.AppendLine("</table>");

            // Emergency contacts
            sb.AppendLine("<h2>Emergency Contacts</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tr><th>Primary</th><td>" +
                          Html(resident.EmergencyContactName1) + " / " +
                          Html(resident.EmergencyContactPhone1) + " / " +
                          Html(resident.EmergencyRelationship1) + "</td></tr>");
            sb.AppendLine("<tr><th>Secondary</th><td>" +
                          Html(resident.EmergencyContactName2) + " / " +
                          Html(resident.EmergencyContactPhone2) + " / " +
                          Html(resident.EmergencyRelationship2) + "</td></tr>");
            sb.AppendLine("</table>");

            // Medications (match your Medication.cs)
            sb.AppendLine("<h2>Current Medications</h2>");
            if (meds.Count == 0)
            {
                sb.AppendLine("<div class='chip'>No medications found</div>");
            }
            else
            {
                sb.AppendLine("<table>");
                sb.AppendLine("<tr><th>Name</th><th>Dosage</th><th>Schedule</th><th>Qty</th><th>Expiry</th></tr>");

                foreach (var m in meds.OrderBy(x => x.MedName))
                {
                    var schedule = Html(m.ScheduleSummary);
                    var expiry = m.ExpiryDate != default ? m.ExpiryDate.ToString("yyyy-MM-dd") : "";

                    sb.AppendLine("<tr>");
                    sb.AppendLine($"<td>{Html(m.MedName)}</td>");
                    sb.AppendLine($"<td>{Html(m.Dosage)}</td>");
                    sb.AppendLine($"<td>{schedule}</td>");
                    sb.AppendLine($"<td>{m.Quantity} {Html(m.QuantityUnit)}</td>");
                    sb.AppendLine($"<td>{Html(expiry)}</td>");
                    sb.AppendLine("</tr>");
                }

                sb.AppendLine("</table>");
            }

            // Observations
            sb.AppendLine("<h2>Recent Observations</h2>");
            if (observations.Count == 0)
            {
                sb.AppendLine("<div class='chip'>No observations recorded</div>");
            }
            else
            {
                sb.AppendLine("<table>");
                sb.AppendLine("<tr><th>Date/Time</th><th>BP</th><th>Temp (°C)</th><th>HR</th><th>SpO2</th><th>Note</th></tr>");

                foreach (var o in observations
                    .OrderByDescending(x => x.ObservedAt)
                    .Take(10))
                {
                    var v = o.Vitals;

                    var bp = (v?.Systolic.HasValue == true && v?.Diastolic.HasValue == true)
                        ? $"{v.Systolic}/{v.Diastolic}"
                        : "";

                    sb.AppendLine("<tr>");
                    sb.AppendLine($"<td>{o.ObservedAt:yyyy-MM-dd HH:mm}</td>");
                    sb.AppendLine($"<td>{Html(bp)}</td>");
                    sb.AppendLine($"<td>{(v?.TemperatureC.HasValue == true ? v.TemperatureC.Value.ToString("0.0") : "")}</td>");
                    sb.AppendLine($"<td>{(v?.HeartRate?.ToString() ?? "")}</td>");
                    sb.AppendLine($"<td>{(v?.OxygenSaturation?.ToString() ?? "")}</td>");
                    sb.AppendLine($"<td>{Html(o.Note)}</td>");
                    sb.AppendLine("</tr>");
                }

                sb.AppendLine("</table>");
            }

            sb.AppendLine("<hr/>");
            sb.AppendLine("<div class='muted'>This report is generated for reference. Clinical decisions must be made by qualified professionals.</div>");
            sb.AppendLine("</body></html>");

            return sb.ToString();
        }

        private static string Html(string? s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("&", "&amp;")
                    .Replace("<", "&lt;")
                    .Replace(">", "&gt;")
                    .Replace("\"", "&quot;");
        }
    }
}
