Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220080639_InitialCreate') THEN
    CREATE TABLE "Residents" (
        "Id" uuid NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "DateOfBirth" date,
        "AdmissionDate" date,
        "RoomNumber" text NOT NULL,
        CONSTRAINT "PK_Residents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220080639_InitialCreate') THEN
    CREATE TABLE "Medications" (
        "Id" uuid NOT NULL,
        "ResidentId" uuid NOT NULL,
        "Name" text NOT NULL,
        "Dosage" text NOT NULL,
        "Frequency" text NOT NULL,
        "Notes" text NOT NULL,
        CONSTRAINT "PK_Medications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Medications_Residents_ResidentId" FOREIGN KEY ("ResidentId") REFERENCES "Residents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220080639_InitialCreate') THEN
    CREATE TABLE "Observations" (
        "Id" uuid NOT NULL,
        "ResidentId" uuid NOT NULL,
        "RecordedAtUtc" timestamp with time zone NOT NULL,
        "Type" text NOT NULL,
        "Value" text NOT NULL,
        "RecordedBy" text NOT NULL,
        CONSTRAINT "PK_Observations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Observations_Residents_ResidentId" FOREIGN KEY ("ResidentId") REFERENCES "Residents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220080639_InitialCreate') THEN
    CREATE INDEX "IX_Medications_ResidentId" ON "Medications" ("ResidentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220080639_InitialCreate') THEN
    CREATE INDEX "IX_Observations_ResidentId" ON "Observations" ("ResidentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220080639_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220080639_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" DROP COLUMN "Frequency";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" RENAME COLUMN "Notes" TO "QuantityUnit";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" RENAME COLUMN "Name" TO "MedName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ALTER COLUMN "ResidentId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ALTER COLUMN "Id" TYPE integer;
    ALTER TABLE "Medications" ALTER COLUMN "Id" DROP DEFAULT;
    ALTER TABLE "Medications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ExpiryDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "FriTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "FriTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "FriTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "IsDone" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "MonTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "MonTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "MonTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "Quantity" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderFri" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderMon" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderSat" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderSun" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderThu" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderTue" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReminderWed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ReorderLevel" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ResidentName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "SatTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "SatTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "SatTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "StockQuantity" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "SunTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "SunTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "SunTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ThuTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ThuTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "ThuTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "TimesPerDay" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "TueTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "TueTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "TueTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "Usage" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "WedTime1" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "WedTime2" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    ALTER TABLE "Medications" ADD "WedTime3" interval NOT NULL DEFAULT INTERVAL '00:00:00';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223080959_CreateMedicationsClean') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260223080959_CreateMedicationsClean', '8.0.0');
    END IF;
END $EF$;
COMMIT;


