// <auto-generated />
using System;
using MedReminder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedReminder.Api.Migrations
{
    [DbContext(typeof(CareHubDbContext))]
    [Migration("20260223233351_M2_SeedMedications")]
    partial class M2_SeedMedications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedReminder.Api.Entities.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("FriTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("FriTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("FriTime3")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("MedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("MonTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MonTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MonTime3")
                        .HasColumnType("interval");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReminderFri")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderMon")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderSat")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderSun")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderThu")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderTue")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderWed")
                        .HasColumnType("boolean");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResidentName")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("SatTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SatTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SatTime3")
                        .HasColumnType("interval");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SunTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SunTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SunTime3")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ThuTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ThuTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ThuTime3")
                        .HasColumnType("interval");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TueTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TueTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TueTime3")
                        .HasColumnType("interval");

                    b.Property<string>("Usage")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("WedTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("WedTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("WedTime3")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("MedReminder.Api.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("MedReminder.Api.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("MedReminder.Api.Entities.Medication", b =>
                {
                    b.HasOne("MedReminder.Api.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedReminder.Api.Entities.Observation", b =>
                {
                    b.HasOne("MedReminder.Api.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
