// <auto-generated />
using System;
using CareHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareHub.Api.Migrations
{
    [DbContext(typeof(CareHubDbContext))]
    [Migration("20260302020401_AddAppUser")]
    partial class AddAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareHub.Api.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CareHub.Api.Entities.MarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdministeredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AdministeredByStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DoseQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DoseUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicationOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId")
                        .IsUnique();

                    b.HasIndex("MedicationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("MarEntries");
                });

            modelBuilder.Entity("CareHub.Api.Entities.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("FriTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("FriTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("FriTime3")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("MedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("MonTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MonTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MonTime3")
                        .HasColumnType("interval");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReminderFri")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderMon")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderSat")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderSun")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderThu")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderTue")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderWed")
                        .HasColumnType("boolean");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResidentName")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("SatTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SatTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SatTime3")
                        .HasColumnType("interval");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SunTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SunTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("SunTime3")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ThuTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ThuTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ThuTime3")
                        .HasColumnType("interval");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TueTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TueTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TueTime3")
                        .HasColumnType("interval");

                    b.Property<string>("Usage")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("WedTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("WedTime2")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("WedTime3")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("CareHub.Api.Entities.MedicationInventoryLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChangeQty")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarEntryId")
                        .IsUnique();

                    b.HasIndex("MedicationId");

                    b.ToTable("MedicationInventoryLedgers");
                });

            modelBuilder.Entity("CareHub.Api.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("CareHub.Api.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AdmissionDate")
                        .HasColumnType("text");

                    b.Property<bool>("AllergyAspirin")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyEggs")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyFish")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyLatex")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyMilk")
                        .HasColumnType("boolean");

                    b.Property<string>("AllergyOtherItems")
                        .HasColumnType("text");

                    b.Property<bool>("AllergyPeanuts")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyPenicillin")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyShellfish")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergySoy")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergySulfa")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyTreeNuts")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllergyWheat")
                        .HasColumnType("boolean");

                    b.Property<string>("BedLabel")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName2")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone2")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyRelationship1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyRelationship2")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("ResidentFName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ResidentFName");

                    b.Property<string>("ResidentLName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ResidentLName");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomType")
                        .HasColumnType("text");

                    b.Property<string>("SIN")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("CareHub.Api.Entities.MarEntry", b =>
                {
                    b.HasOne("CareHub.Api.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHub.Api.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("CareHub.Api.Entities.Medication", b =>
                {
                    b.HasOne("CareHub.Api.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CareHub.Api.Entities.MedicationInventoryLedger", b =>
                {
                    b.HasOne("CareHub.Api.Entities.MarEntry", "MarEntry")
                        .WithMany()
                        .HasForeignKey("MarEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareHub.Api.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarEntry");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("CareHub.Api.Entities.Observation", b =>
                {
                    b.HasOne("CareHub.Api.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
